### ISSUE TITLE
Tree build fail for many isolates

### ISSUE THREAD

**Issue by schultzm** [lskatz/mashtree#18]
Hi @lskatz ,

Thank you very much for the useful program.  I am trying to run mashtree on more than 1000 isolates, but I am running into a problem.  The error message is below. 

```
mashtree.pl: mashDistance: Converting to phylip format into mash_tmp/distances.phylip
DBD::SQLite::db prepare failed: Expression tree is too large (maximum depth 1000) at /home/linuxbrew/.linuxbrew/Cellar/perl/5.26.1/lib/perl5/site_perl/5.26.1/Mashtree/Db.pm line 301.
mashtree.pl: Mashtree::Db::toString_phylip: DBD::SQLite::db prepare failed: Expression tree is too large (maximum depth 1000)
Stopped at /home/linuxbrew/.linuxbrew/Cellar/perl/5.26.1/lib/perl5/site_perl/5.26.1/Mashtree/Db.pm line 301.
```

Cheers,

**Comment by lskatz** [comment]
Sorry that happened!  @tseemann seems to have a viable solution. I'll try it out next week.

**Comment by rrwick** [comment]
Hi Mark! How funny that you and I hit the same issue in mashtree within a day of each other!

I previously encountered a DBD::SQLite bug in mashtree which I fixed by compiling my own copy of DBD::SQLite, using altered parameters: https://github.com/lskatz/mashtree/issues/11

That old issue is fixed in mashtree, but this expression tree limit is also controlled by a compile-time parameter (SQLITE_MAX_EXPR_DEPTH) so I'm hopeful that I can solve it in the same way.

Here's what I did to build DBD::SQLite:
```
wget http://search.cpan.org/CPAN/authors/id/I/IS/ISHIGAKI/DBD-SQLite-1.54.tar.gz
tar -xf DBD-SQLite-1.54.tar.gz
cd DBD-SQLite-1.54
sed -i 's|SQLITE_MAX_COMPOUND_SELECT 500|SQLITE_MAX_COMPOUND_SELECT 1000000|g' sqlite3.c  # probably no longer necessary
sed -i 's|SQLITE_MAX_EXPR_DEPTH 1000|SQLITE_MAX_EXPR_DEPTH 1000000|g' sqlite3.c  # will hopefully fix expression-tree-too-large crash
perl Makefile.PL INSTALL_BASE=$HOME/.local/perl
make
make install
```

And then I make sure Perl uses my custom build before running mashtree:
```
export PERL5LIB=$HOME/.local/perl/lib/perl5:$HOME/.local/perl/lib/perl5/x86_64-linux-thread-multi:$PERL5LIB
```

I just launched my job again, so I won't know if it worked for a couple of hours. Stay tuned!

Ryan

**Comment by rrwick** [comment]
Well, the tree-building isn't done, but it made it to the "Creating a NJ tree with BioPerl" step, which is further than it got before. So I think the custom DBD::SQLite build works!

**Comment by tseemann** [comment]
@rrwick recompiling SQLite was a solution i wanted to avoid. I think the issue is the mega-batched up INSERT statement @lskatz is using.  I'm hoping my solution in #19 works.

(at first i thought it was `ulimit -a` 1024 open files but it isn't)

**Comment by egonozer** [comment]
I ran into this same problem a few days ago building a tree from over 2000 assemblies. I also didn't want to recompile SQLite, so here's the solution I hacked based on a stackoverflow post I found (https://stackoverflow.com/questions/9570197/sqlite-expression-maximum-depth-limit). There were two subroutines that needed fixing in lib/Mashtree/Db.pm for this to work, toString_tsv and toString_phylip. Essentially, I just enclosed every 500 OR statements in parentheses with each block of OR statements separated by an OR. 

Here's what that looks like in both subroutines. I changed
```perl
if(@$genome){
   $sql.="WHERE \n";
   for(@$genome){
      $sql.="GENOME1 LIKE '$_%' OR \n";
   }
   $sql=~s/\s*OR\s*$//;
   $sql.="\n";
}
```
to
```perl
if (@$genome){
   $sql.="WHERE (\n";
   my $gcount = 0;
   for(@$genome){
      $sql.="GENOME1 LIKE '$_%' OR \n";
      $gcount++;
      if ($gcount == 500){
         $sql=~s/\s*OR\s*$//;
         $sql.= ")\n OR (\n";
         $gcount = 0;
      }
   }
   $sql=~s/\)*\s*OR\s*\(*\s*$//;
   $sql.=")\n";
}
```
Ran to completion with the output I would have expected. I know it's not necessarily infinitely scalable (what happens if you include so many genomes that you end up with over 1000 of these 500 OR blocks?), but it seems like it would work up to an insanely high limit. I think you could set the $gcount limit at 999 and it would still theoretically work, but I haven't tried that.

Torsten's solution in issue #19 looks like it might be a lot more elegant, but I won't pretend to know much about SQLite. Just sharing what worked for me.

**Comment by tseemann** [comment]
@egonozer doesn't the current version of mashtree already do this? (break into 500)

**Comment by egonozer** [comment]
@tseemann Not that I'm aware of. My comment above showed the code as downloaded in the first block and after my edits in the second block.  Just for a little more context, the additions I made are just before the `my $sth=$dbh->prepare($sql);` statements in both of the `toString_tsv` (line 263) and `toString_phylip` (line 301) subroutines in the lib/Mashtree/Db.pm module. Those were the lines giving me the  "Expression Tree is too large" errors before I added the extra parentheses for each group of 500.  My error message was almost identical to @schultzm before I made the edits.

**Comment by lskatz** [comment]
I _think_ I fixed the issue by removing the conditionals in SQL and moving that logic into perl.  So, hypothetically slower (SQL faster than Perl), but more stable.  However, it would take > 30 minutes to test this on 1000 genomes.  I also added in the `prepare` statements that @tseemann suggested.  Could you see if it fixes it on your end @egonozer?  These changes are reflected in 239f73d but are not a tagged version yet.
