### ISSUE TITLE
Select outgroup 

### ISSUE THREAD

**Issue by annabananakobana** [lskatz/mashtree#56]
Hi team, 

Currently generating a guide tree for a group of marsupials, yet mashtree is grouping my placental mammals within the marsupial lineages. 

Would you please be able to write some software so that we can define our outgroup species relative to current evolutionary understanding (ie. marsupials, monotremes and placental mammals are independent lineages). 

Cheers,
Anna

**Comment by lskatz** [comment]
Hi @annabananakobana!  I am flattered that mashtree has made its way into eukarya!

Designating an outgroup was a feature I was considering a long time ago, but I abandoned it because any tree interface will let you designate the outgroup on a tree file.  How are you visualizing the tree?  In MEGA for example, there is a menu option to click an outgroup and then root on it.

**Comment by lskatz** [comment]
One more comment I want to make is that I want to be sure you know this is not a phylogenetic program.  It only clusters.  I agree that evolutionary understanding should guide us on how the tree should look, but there is no evolutionary principle in play here.

**Comment by annabananakobana** [comment]
Hi @lskatz! 

Thanks for the update! I am currently using figtree for visualisation, but both the midpoint and user selections were throwing the relationships. You make an excellent point regarding the restricted inference for true evo relationships. I am updating a current alignment that has used Mash distances so was keeping the analysis consistent, so will check a couple of things before proceeding :)
